// this is auto generated by next-js
// that's why we're disabling this eslint rule
/* eslint-disable unicorn/prevent-abbreviations */
/// <reference types="next" />
/// <reference types="next/types/global" />
/// <reference types="next/image-types/global" />
